### ISSUE TITLE
How do I install the package

### ISSUE THREAD

**Issue by murum** [daylerees/anbu#7]
Please add further information in the readme how to install the package since there's no Composer package or where to place the code instructions. 

It would also be good to see how I can only apply this anbu profiler to a dev environment, maybe that's already working I don't know since I can't test it. :) 

Thanks in advice!

**Comment by garfield58** [comment]
hey Murum,

require: "daylerees/anbu": "dev-master"

**Comment by pratyushpundir** [comment]
That's right. It's already available thru packagist as a dev-master. I have added the required Service Provider to my Local/Development config file in Laravel so I did not have it running for production. Not sure if that is the way to go but it works fine so far. 

Since this is an alpha right now, We'll have to wait for proper documentation to come up, however, knowing Dayle Reese, it should be coming soon!!

**Comment by daylerees** [comment]
I'll add this to the repo mate. Thanks!

**Comment by daylerees** [comment]
Better instructions now. Thanks guys!
